Repository ionic-team/capacitor-plugins, pull requests merged in 2023-08, with the labels that each got.

#1712 docs(google-maps): Update the workaround note to use the released version
  google-maps/README.md
Labels: pr review requested

#1595 feat(google-maps): Update map size in updateRender method if it has changed
  google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
  google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
  google-maps/e2e-tests/src/pages/Map/ResizeMap.tsx
  google-maps/e2e-tests/src/routes.ts
  google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.m
  google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift
  google-maps/ios/Plugin/Map.swift
  google-maps/package.json
  google-maps/src/implementation.ts
  google-maps/src/map.ts
  google-maps/src/web.ts
Labels: type: feature request

#1601 feat(google-maps): Added feature to disable touch events on map
  google-maps/README.md
  google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
  google-maps/e2e-tests/src/pages/Map/CreateAndDestroyMap.tsx
  google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.m
  google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift
  google-maps/ios/Plugin/Map.swift
  google-maps/src/implementation.ts
  google-maps/src/map.ts
  google-maps/src/web.ts
Labels: type: feature request

#1638 fix(google-maps): attach native map view to correct scroll view
  google-maps/e2e-tests/src/pages/Scrolling/SimpleScrolling.tsx
  google-maps/ios/Plugin/Map.swift
  google-maps/src/map.ts
Labels: type: bug

#1669 feat(browser): support other custom tabs providers
  browser/android/src/main/AndroidManifest.xml
  browser/android/src/main/java/com/capacitorjs/plugins/browser/Browser.java
Labels: type: feature request, pr review requested

#1660 fix(filesystem): accessing security scoped resources on iOS
  filesystem/ios/Plugin/Filesystem.swift
Labels: type: feature request, pr review requested
